Repository E3SM-Project/zstash, pull requests merged in 2021-05, with the labels that each got.

#143 Update docs for v1.1.0
  docs/source/database.rst
  docs/source/index.rst
  docs/source/tutorial.rst
  docs/source/usage.rst
Labels: documentation, for next version

#147 Add conda channel label assignment in release workflow
  .github/workflows/release_workflow.yml
Labels: DevOps

#148 Update to v1.1.0rc1
  conda/meta.yaml
  setup.py
  zstash/__init__.py
Labels: update version

#150 Update source section of meta.yaml
  conda/meta.yaml
Labels: DevOps
