Repository E3SM-Project/zstash, pull requests merged in 2021-04, with the labels that each got.

#130 Add and apply QA tools to the repository
  .github/workflows/workflow.yml
  .pre-commit-config.yaml
  .vscode/settings.json
  README.md
  conda/dev.yml
  conda/meta.yaml
  docs/source/_static/pre-commit-passing.png
  docs/source/conf.py
  docs/source/dev_guide/git-flow.svg
  docs/source/dev_guide/index.rst
  docs/source/dev_guide/pre-commit-flow.svg
  docs/source/dev_guide/project-standards.rst
  docs/source/dev_guide/release.rst
  docs/source/getting_started.rst
  docs/source/index.rst
  setup.cfg
  setup.py
  tests/__init__.py
  tests/base.py
  tests/test_check.py
  tests/test_check_parallel.py
  tests/test_chgrp.py
  tests/test_create.py
  tests/test_extract.py
  tests/test_extract_parallel.py
  tests/test_ls.py
  tests/test_update.py
  zstash/__init__.py
  zstash/check.py
  zstash/chgrp.py
  zstash/create.py
  zstash/extract.py
  zstash/hpss.py
  zstash/hpss_utils.py
  zstash/ls.py
  zstash/main.py
  zstash/parallel.py
  zstash/settings.py
  zstash/update.py
  zstash/utils.py
Labels: DevOps

#135 Add GitHub Actions release workflow
  .github/workflows/build_workflow.yml
  .github/workflows/release_workflow.yml
  README.md
  docs/source/contributing.rst
  docs/source/dev_guide/github_release.png
  docs/source/dev_guide/project-standards.rst
  docs/source/dev_guide/release.rst
Labels: DevOps

#138 Improve readability
  tests/base.py
  tests/test_check.py
  tests/test_check_parallel.py
  tests/test_extract.py
  zstash/chgrp.py
  zstash/create.py
  zstash/extract.py
  zstash/hpss.py
  zstash/hpss_utils.py
  zstash/ls.py
  zstash/main.py
  zstash/parallel.py
  zstash/settings.py
  zstash/update.py
  zstash/utils.py
Labels: enhancement, nice to have

#140 Add checksums for tar files
  tests/base.py
  tests/test_ls.py
  zstash/create.py
  zstash/extract.py
  zstash/hpss_utils.py
  zstash/ls.py
  zstash/settings.py
  zstash/utils.py
Labels: new feature, nice to have
