Repository E3SM-Project/zstash, pull requests merged in 2022-11, with the labels that each got.

#227 Perlmutter support
  docs/source/best_practices.rst
  docs/source/getting_started.rst
  docs/source/tutorial.rst
Labels: High priority

#231 Bump to 1.3.0rc1
  conda/meta.yaml
  setup.py
  tbump.toml
  zstash/__init__.py
Labels: Update version

#214 Globus transfer optimization
  zstash/create.py
  zstash/globus.py
  zstash/hpss.py
  zstash/hpss_utils.py
  zstash/update.py
Labels: Globus, High priority

#235 Add Perlmutter endpoints
  tests/test_globus.py
  zstash/globus.py
Labels: High priority

#237 Bump to 1.3.0rc2
  conda/meta.yaml
  setup.py
  tbump.toml
  zstash/__init__.py
Labels: Update version
