Repository E3SM-Project/zstash, pull requests merged in 2022-01, with the labels that each got.

#154 Extend --hpss to accept a Globus URL
  .gitignore
  docs/source/tutorial.rst
  docs/source/usage.rst
  setup.py
  tests/test_globus.py
  zstash/create.py
  zstash/extract.py
  zstash/globus.py
  zstash/hpss.py
  zstash/hpss_utils.py
  zstash/ls.py
  zstash/update.py
Labels: for next version, new feature, Globus

#179 Fix tests
  tests/test_chgrp.py
  tests/test_globus.py
Labels: testing, for next version, Globus

#177 Remove keep from config
  zstash/create.py
  zstash/extract.py
  zstash/hpss_utils.py
  zstash/ls.py
  zstash/settings.py
  zstash/update.py
Labels: for next version, nice to have

#181 Improve docs on check
  docs/source/usage.rst
Labels: documentation

#182 Improve docs on keep
  docs/source/usage.rst
Labels: documentation

#184 Bump to 1.2.0rc1
  conda/meta.yaml
  setup.py
  tbump.toml
  zstash/__init__.py
Labels: update version

#186 Fix conda requirements
  conda/dev.yml
  conda/meta.yaml
Labels: bug

#187 Bump to 1.2.0rc2
  conda/meta.yaml
  setup.py
  tbump.toml
  zstash/__init__.py
Labels: update version

#188 Fix globus-sdk conda error
  conda/meta.yaml
Labels: bug, DevOps

#189 Bump to 1.2.0rc3
  conda/meta.yaml
  setup.py
  tbump.toml
  zstash/__init__.py
Labels: update version
